# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ♥	♥	♥	 Yoganjali (Diya) - Vinutnaanjali (Vinny) ♥	♥	♥
punchline: We love you Diya and Vinny
email: kumar.kunche@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This page contains all the memories of Diya and Vinny ever since they were born.
  Their Smile makes us smile. Their laugh is infectious. Their hearts are
  pure and true. Above all we love that they are our lil ones..♥
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  dannyboje

# Build settings
markdown: kramdown
